export const adminbar_data = {
    "new-content": {
        icon: "dashicons dashicons-plus",
        id: "new-content",
        title: '<span class="ab-icon" aria-hidden="true"></span><span class="ab-label">New</span>',
        parent: false,
        href: "http://localhost:10043/wp-admin/post-new.php",
        group: false,
        meta: { menu_title: "New" },
        submenu: {
            "new-post": {
                icon: "",
                id: "new-post",
                title: "Post",
                parent: "new-content",
                href: "http://localhost:10043/wp-admin/post-new.php",
                group: false,
                meta: [],
                submenu: [],
                menu_level: 1,
                menu_status: true,
                title_encoded: "Post",
                title_clean: "Post",
                title_encoded_default: "",
                title_clean_default: "",
            },
            "new-media": {
                icon: "",
                id: "new-media",
                title: "Media",
                parent: "new-content",
                href: "http://localhost:10043/wp-admin/media-new.php",
                group: false,
                meta: [],
                submenu: [],
                menu_level: 1,
                menu_status: true,
                title_encoded: "Media",
                title_clean: "Media",
                title_encoded_default: "",
                title_clean_default: "",
            },
            "new-page": {
                icon: "",
                id: "new-page",
                title: "Page",
                parent: "new-content",
                href: "http://localhost:10043/wp-admin/post-new.php?post_type=page",
                group: false,
                meta: [],
                submenu: [],
                menu_level: 1,
                menu_status: true,
                title_encoded: "Page",
                title_clean: "Page",
                title_encoded_default: "",
                title_clean_default: "",
            },
            "new-user": {
                icon: "",
                id: "new-user",
                title: "User",
                parent: "new-content",
                href: "http://localhost:10043/wp-admin/user-new.php",
                group: false,
                meta: [],
                submenu: [],
                menu_level: 1,
                menu_status: true,
                title_encoded: "User",
                title_clean: "User",
                title_encoded_default: "",
                title_clean_default: "",
            },
        },
        menu_level: 0,
        menu_status: true,
        title_encoded:
            "&lt;span class=&quot;ab-icon&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;span class=&quot;ab-label&quot;&gt;New&lt;/span&gt;",
        title_clean: "New",
        title_encoded_default: "",
        title_clean_default: "",
    },
    "wp-adminify-settings": {
        icon: "",
        id: "wp-adminify-settings",
        title: "WP Adminify",
        parent: false,
        href: "http://localhost:10043/wp-admin/admin.php?page=wp-adminify-settings",
        group: false,
        meta: [],
        submenu: {
            "wp-adminify-settings-0": {
                icon: "",
                id: "wp-adminify-settings-0",
                title: "WP Adminify",
                parent: "wp-adminify-settings",
                href: "http://localhost:10043/wp-admin/admin.php?page=wp-adminify-settings",
                group: false,
                meta: [],
                submenu: [],
                menu_level: 1,
                menu_status: true,
                title_encoded: "WP Adminify",
                title_clean: "WP Adminify",
                title_encoded_default: "",
                title_clean_default: "",
            },
            "wp-adminify-settings-1": {
                icon: "",
                id: "wp-adminify-settings-1",
                title: "User Role Editor",
                parent: "wp-adminify-settings",
                href: "http://localhost:10043/wp-admin/admin.php?page=rolemaster-suite-editor",
                group: false,
                meta: [],
                submenu: [],
                menu_level: 1,
                menu_status: true,
                title_encoded: "User Role Editor",
                title_clean: "User Role Editor",
                title_encoded_default: "",
                title_clean_default: "",
            },
            "wp-adminify-settings-2": {
                icon: "",
                id: "wp-adminify-settings-2",
                title: "Adminbar Editor",
                parent: "wp-adminify-settings",
                href: "http://localhost:10043/wp-admin/admin.php?page=jlt_admin_bar_editor-settings",
                group: false,
                meta: [],
                submenu: [],
                menu_level: 1,
                menu_status: true,
                title_encoded: "Adminbar Editor",
                title_clean: "Adminbar Editor",
                title_encoded_default: "",
                title_clean_default: "",
            },
            "wp-adminify-settings-3": {
                icon: "",
                id: "wp-adminify-settings-3",
                title: "Setup Wizard",
                parent: "wp-adminify-settings",
                href: "http://localhost:10043/wp-admin/admin.php?page=index.php?page=wp-adminify-setup-wizard",
                group: false,
                meta: [],
                submenu: [],
                menu_level: 1,
                menu_status: true,
                title_encoded: "Setup Wizard",
                title_clean: "Setup Wizard",
                title_encoded_default: "",
                title_clean_default: "",
            },
            "wp-adminify-settings-4": {
                icon: "",
                id: "wp-adminify-settings-4",
                title: '<span class="adminify-addons-text">Addons</span>',
                parent: "wp-adminify-settings",
                href: "http://localhost:10043/wp-admin/admin.php?page=wp-adminify-addons-plugins",
                group: false,
                meta: [],
                submenu: [],
                menu_level: 1,
                menu_status: true,
                title_encoded:
                    "&lt;span class=&quot;adminify-addons-text&quot;&gt;Addons&lt;/span&gt;",
                title_clean: "Addons",
                title_encoded_default: "",
                title_clean_default: "",
            },
            "wp-adminify-settings-5": {
                icon: "",
                id: "wp-adminify-settings-5",
                title: '<span class="fs-submenu-item adminify account ">Account</span>',
                parent: "wp-adminify-settings",
                href: "http://localhost:10043/wp-admin/admin.php?page=wp-adminify-settings-account",
                group: false,
                meta: [],
                submenu: [],
                menu_level: 1,
                menu_status: true,
                title_encoded:
                    "&lt;span class=&quot;fs-submenu-item adminify account &quot;&gt;Account&lt;/span&gt;",
                title_clean: "Account",
                title_encoded_default: "",
                title_clean_default: "",
            },
            "wp-adminify-settings-6": {
                icon: "",
                id: "wp-adminify-settings-6",
                title: '<span class="fs-submenu-item adminify pricing upgrade-mode">Upgrade&nbsp;&nbsp;&#x27a4;</span>',
                parent: "wp-adminify-settings",
                href: "http://localhost:10043/wp-admin/admin.php?page=wp-adminify-settings-pricing",
                group: false,
                meta: [],
                submenu: [],
                menu_level: 1,
                menu_status: true,
                title_encoded:
                    "&lt;span class=&quot;fs-submenu-item adminify pricing upgrade-mode&quot;&gt;Upgrade&nbsp;&nbsp;&amp;#x27a4;&lt;/span&gt;",
                title_clean: "Upgrade&nbsp;&nbsp;&#x27a4;",
                title_encoded_default: "",
                title_clean_default: "",
            },
        },
        menu_level: 0,
        menu_status: true,
        title_encoded: "WP Adminify",
        title_clean: "WP Adminify",
        title_encoded_default: "",
        title_clean_default: "",
    },
    "top-secondary": {
        icon: "",
        id: "top-secondary",
        title: false,
        parent: false,
        href: false,
        group: true,
        meta: { class: "ab-top-secondary" },
        submenu: {
            "my-account": {
                icon: "",
                id: "my-account",
                title: "Howdy <span class=\"display-name\">Kakon Barman</span><img alt='' src='http://0.gravatar.com/avatar/f932d57c660fac86f2a427e2dff84ac8?s=26&#038;d=mm&#038;r=g' srcset='http://0.gravatar.com/avatar/f932d57c660fac86f2a427e2dff84ac8?s=52&#038;d=mm&#038;r=g 2x' class='avatar avatar-26 photo' height='26' width='26' loading='lazy' decoding='async'/>",
                parent: "top-secondary",
                href: "http://localhost:10043/wp-admin/profile.php",
                group: false,
                meta: { class: "with-avatar", menu_title: "Howdy, Kakon Barman", tabindex: "" },
                submenu: {
                    "user-actions": {
                        icon: "",
                        id: "user-actions",
                        title: false,
                        parent: "my-account",
                        href: false,
                        group: true,
                        meta: [],
                        submenu: {
                            "user-info": {
                                icon: "",
                                id: "user-info",
                                title: "<img alt='' src='http://0.gravatar.com/avatar/f932d57c660fac86f2a427e2dff84ac8?s=64&#038;d=mm&#038;r=g' srcset='http://0.gravatar.com/avatar/f932d57c660fac86f2a427e2dff84ac8?s=128&#038;d=mm&#038;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' loading='lazy' decoding='async'/><span class='display-name'>Kakon Barman</span><span class='username'>admin</span><span class='display-name edit-profile'>Edit Profile</span>",
                                parent: "user-actions",
                                href: "http://localhost:10043/wp-admin/profile.php",
                                group: false,
                                meta: [],
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;img alt=&#039;&#039; src=&#039;http://0.gravatar.com/avatar/f932d57c660fac86f2a427e2dff84ac8?s=64&#038;d=mm&#038;r=g&#039; srcset=&#039;http://0.gravatar.com/avatar/f932d57c660fac86f2a427e2dff84ac8?s=128&#038;d=mm&#038;r=g 2x&#039; class=&#039;avatar avatar-64 photo&#039; height=&#039;64&#039; width=&#039;64&#039; loading=&#039;lazy&#039; decoding=&#039;async&#039;/&gt;&lt;span class=&#039;display-name&#039;&gt;Kakon Barman&lt;/span&gt;&lt;span class=&#039;username&#039;&gt;admin&lt;/span&gt;&lt;span class=&#039;display-name edit-profile&#039;&gt;Edit Profile&lt;/span&gt;",
                                title_clean: "Kakon BarmanadminEdit Profile",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            logout: {
                                icon: "",
                                id: "logout",
                                title: "Log Out",
                                parent: "user-actions",
                                href: "http://localhost:10043/wp-login.php?action=logout&amp;_wpnonce=77168bcc37",
                                group: false,
                                meta: [],
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded: "Log Out",
                                title_clean: "Log Out",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                        },
                        menu_level: 2,
                        menu_status: true,
                        title_encoded: "",
                        title_clean: "",
                        title_encoded_default: "",
                        title_clean_default: "",
                    },
                },
                menu_level: 1,
                menu_status: true,
                title_encoded:
                    "Howdy &lt;span class=&quot;display-name&quot;&gt;Kakon Barman&lt;/span&gt;&lt;img alt=&#039;&#039; src=&#039;http://0.gravatar.com/avatar/f932d57c660fac86f2a427e2dff84ac8?s=26&#038;d=mm&#038;r=g&#039; srcset=&#039;http://0.gravatar.com/avatar/f932d57c660fac86f2a427e2dff84ac8?s=52&#038;d=mm&#038;r=g 2x&#039; class=&#039;avatar avatar-26 photo&#039; height=&#039;26&#039; width=&#039;26&#039; loading=&#039;lazy&#039; decoding=&#039;async&#039;/&gt;",
                title_clean: "Howdy Kakon Barman",
                title_encoded_default: "",
                title_clean_default: "",
            },
            vaa: {
                icon: "",
                id: "vaa",
                title: '<span class="ab-label">View As</span><span class="ab-icon dashicons dashicons-hidden alignright" aria-hidden="true"></span>',
                parent: "top-secondary",
                href: false,
                group: false,
                meta: { title: "View Admin As", tabindex: "0" },
                submenu: {
                    "vaa-info": {
                        icon: "",
                        id: "vaa-info",
                        title: '<span class="ab-icon dashicons dashicons-info" aria-hidden="true"></span>Info',
                        parent: "vaa",
                        href: false,
                        group: false,
                        meta: { class: "vaa-has-icon", tabindex: "0" },
                        submenu: {
                            "vaa-info-about": {
                                icon: "",
                                id: "vaa-info-about",
                                title: false,
                                parent: "vaa-info",
                                href: false,
                                group: true,
                                meta: { class: "ab-sub-secondary" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded: "",
                                title_clean: "",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-info-links": {
                                icon: "",
                                id: "vaa-info-links",
                                title: false,
                                parent: "vaa-info",
                                href: false,
                                group: true,
                                meta: [],
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded: "",
                                title_clean: "",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                        },
                        menu_level: 2,
                        menu_status: true,
                        title_encoded:
                            "&lt;span class=&quot;ab-icon dashicons dashicons-info&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;Info",
                        title_clean: "Info",
                        title_encoded_default: "",
                        title_clean_default: "",
                    },
                    "vaa-settings": {
                        icon: "",
                        id: "vaa-settings",
                        title: '<span class="ab-icon dashicons dashicons-admin-settings" aria-hidden="true"></span>Settings',
                        parent: "vaa",
                        href: false,
                        group: false,
                        meta: { class: "vaa-has-icon", tabindex: "0" },
                        submenu: {
                            "vaa-settings-admin-menu-location": {
                                icon: "",
                                id: "vaa-settings-admin-menu-location",
                                title: '<span class="ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide" vaa-showhide=".vaa-settings-admin-menu-location-desc" aria-hidden="true"></span><label class="ab-vaa-showhide" for="vaa-settings-admin-menu-location">Location: &nbsp; </label><select id="vaa-settings-admin-menu-location" name="vaa_settings_admin_menu_location" class="selectbox" vaa-auto-js="{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:true,&quot;values&quot;:{&quot;admin_menu_location&quot;:null}}"><option value="top-secondary"  selected=\'selected\'>Default</option><option value="my-account" >My account</option></select><p class="ab-item description vaa-settings-admin-menu-location-desc">Change the location of this menu node</p>',
                                parent: "vaa-settings",
                                href: false,
                                group: false,
                                meta: { class: "auto-height ab-vaa-select" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide&quot; vaa-showhide=&quot;.vaa-settings-admin-menu-location-desc&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;label class=&quot;ab-vaa-showhide&quot; for=&quot;vaa-settings-admin-menu-location&quot;&gt;Location: &nbsp; &lt;/label&gt;&lt;select id=&quot;vaa-settings-admin-menu-location&quot; name=&quot;vaa_settings_admin_menu_location&quot; class=&quot;selectbox&quot; vaa-auto-js=&quot;{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:true,&quot;values&quot;:{&quot;admin_menu_location&quot;:null}}&quot;&gt;&lt;option value=&quot;top-secondary&quot;  selected=&#039;selected&#039;&gt;Default&lt;/option&gt;&lt;option value=&quot;my-account&quot; &gt;My account&lt;/option&gt;&lt;/select&gt;&lt;p class=&quot;ab-item description vaa-settings-admin-menu-location-desc&quot;&gt;Change the location of this menu node&lt;/p&gt;",
                                title_clean:
                                    "Location: &nbsp; DefaultMy accountChange the location of this menu node",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-settings-view-mode": {
                                icon: "",
                                id: "vaa-settings-view-mode",
                                title: '<div class="vaa-radio-wrapper"><span class="ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide" vaa-showhide=".vaa-settings-view-mode-browse-desc" aria-hidden="true"></span><input type="radio" id="vaa-settings-view-mode-browse" name="vaa_settings_view_mode" value="browse" class="radio vaa-settings-view-mode" vaa-auto-js="{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:false,&quot;values&quot;:{&quot;view_mode&quot;:null}}"  checked=\'checked\'/><label class="ab-vaa-showhide" for="vaa-settings-view-mode-browse">Browse mode</label><br><p class="ab-item description vaa-settings-view-mode-browse-desc">Store view and use WordPress with this view</p></div><div class="vaa-radio-wrapper"><span class="ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide" vaa-showhide=".vaa-settings-view-mode-single-desc" aria-hidden="true"></span><input type="radio" id="vaa-settings-view-mode-single" name="vaa_settings_view_mode" value="single" class="radio vaa-settings-view-mode" vaa-auto-js="{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:false,&quot;values&quot;:{&quot;view_mode&quot;:null}}" /><label class="ab-vaa-showhide" for="vaa-settings-view-mode-single">Single switch mode</label><br><p class="ab-item description vaa-settings-view-mode-single-desc">Choose view on every pageload. This setting doesn\'t store views</p></div>',
                                parent: "vaa-settings",
                                href: false,
                                group: false,
                                meta: { class: "auto-height" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;div class=&quot;vaa-radio-wrapper&quot;&gt;&lt;span class=&quot;ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide&quot; vaa-showhide=&quot;.vaa-settings-view-mode-browse-desc&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;input type=&quot;radio&quot; id=&quot;vaa-settings-view-mode-browse&quot; name=&quot;vaa_settings_view_mode&quot; value=&quot;browse&quot; class=&quot;radio vaa-settings-view-mode&quot; vaa-auto-js=&quot;{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:false,&quot;values&quot;:{&quot;view_mode&quot;:null}}&quot;  checked=&#039;checked&#039;/&gt;&lt;label class=&quot;ab-vaa-showhide&quot; for=&quot;vaa-settings-view-mode-browse&quot;&gt;Browse mode&lt;/label&gt;&lt;br&gt;&lt;p class=&quot;ab-item description vaa-settings-view-mode-browse-desc&quot;&gt;Store view and use WordPress with this view&lt;/p&gt;&lt;/div&gt;&lt;div class=&quot;vaa-radio-wrapper&quot;&gt;&lt;span class=&quot;ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide&quot; vaa-showhide=&quot;.vaa-settings-view-mode-single-desc&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;input type=&quot;radio&quot; id=&quot;vaa-settings-view-mode-single&quot; name=&quot;vaa_settings_view_mode&quot; value=&quot;single&quot; class=&quot;radio vaa-settings-view-mode&quot; vaa-auto-js=&quot;{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:false,&quot;values&quot;:{&quot;view_mode&quot;:null}}&quot; /&gt;&lt;label class=&quot;ab-vaa-showhide&quot; for=&quot;vaa-settings-view-mode-single&quot;&gt;Single switch mode&lt;/label&gt;&lt;br&gt;&lt;p class=&quot;ab-item description vaa-settings-view-mode-single-desc&quot;&gt;Choose view on every pageload. This setting doesn&#039;t store views&lt;/p&gt;&lt;/div&gt;",
                                title_clean:
                                    "Browse modeStore view and use WordPress with this viewSingle switch modeChoose view on every pageload. This setting doesn't store views",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-settings-hide-front": {
                                icon: "",
                                id: "vaa-settings-hide-front",
                                title: '<span class="ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide" vaa-showhide=".vaa-settings-hide-front-desc" aria-hidden="true"></span><input type="checkbox" id="vaa-settings-hide-front" name="vaa_settings_hide_front" value="1" class="checkbox" vaa-auto-js="{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:false,&quot;values&quot;:{&quot;hide_front&quot;:null}}" /><label class="ab-vaa-showhide" for="vaa-settings-hide-front">Hide on frontend</label><p class="ab-item description vaa-settings-hide-front-desc">Hide on frontend when no view is selected and the admin bar is not shown</p>',
                                parent: "vaa-settings",
                                href: false,
                                group: false,
                                meta: { class: "auto-height" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide&quot; vaa-showhide=&quot;.vaa-settings-hide-front-desc&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;input type=&quot;checkbox&quot; id=&quot;vaa-settings-hide-front&quot; name=&quot;vaa_settings_hide_front&quot; value=&quot;1&quot; class=&quot;checkbox&quot; vaa-auto-js=&quot;{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:false,&quot;values&quot;:{&quot;hide_front&quot;:null}}&quot; /&gt;&lt;label class=&quot;ab-vaa-showhide&quot; for=&quot;vaa-settings-hide-front&quot;&gt;Hide on frontend&lt;/label&gt;&lt;p class=&quot;ab-item description vaa-settings-hide-front-desc&quot;&gt;Hide on frontend when no view is selected and the admin bar is not shown&lt;/p&gt;",
                                title_clean:
                                    "Hide on frontendHide on frontend when no view is selected and the admin bar is not shown",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-settings-hide-customizer": {
                                icon: "",
                                id: "vaa-settings-hide-customizer",
                                title: '<span class="ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide" vaa-showhide=".vaa-settings-hide-customizer-desc" aria-hidden="true"></span><input type="checkbox" id="vaa-settings-hide-customizer" name="vaa_settings_hide_customizer" value="1" class="checkbox" vaa-auto-js="{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:false,&quot;values&quot;:{&quot;hide_customizer&quot;:null}}" /><label class="ab-vaa-showhide" for="vaa-settings-hide-customizer">Hide on customizer</label><p class="ab-item description vaa-settings-hide-customizer-desc">Hide on customizer when no view is selected</p>',
                                parent: "vaa-settings",
                                href: false,
                                group: false,
                                meta: { class: "auto-height" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide&quot; vaa-showhide=&quot;.vaa-settings-hide-customizer-desc&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;input type=&quot;checkbox&quot; id=&quot;vaa-settings-hide-customizer&quot; name=&quot;vaa_settings_hide_customizer&quot; value=&quot;1&quot; class=&quot;checkbox&quot; vaa-auto-js=&quot;{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:false,&quot;values&quot;:{&quot;hide_customizer&quot;:null}}&quot; /&gt;&lt;label class=&quot;ab-vaa-showhide&quot; for=&quot;vaa-settings-hide-customizer&quot;&gt;Hide on customizer&lt;/label&gt;&lt;p class=&quot;ab-item description vaa-settings-hide-customizer-desc&quot;&gt;Hide on customizer when no view is selected&lt;/p&gt;",
                                title_clean:
                                    "Hide on customizerHide on customizer when no view is selected",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-settings-freeze-locale": {
                                icon: "",
                                id: "vaa-settings-freeze-locale",
                                title: '<span class="ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide" vaa-showhide=".vaa-settings-freeze-locale-desc" aria-hidden="true"></span><input type="checkbox" id="vaa-settings-freeze-locale" name="vaa_settings_freeze_locale" value="1" class="checkbox" vaa-auto-js="{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:false,&quot;values&quot;:{&quot;freeze_locale&quot;:null}}" /><label class="ab-vaa-showhide" for="vaa-settings-freeze-locale">Freeze locale</label><p class="ab-item description vaa-settings-freeze-locale-desc">Force your own locale setting to the current view</p>',
                                parent: "vaa-settings",
                                href: false,
                                group: false,
                                meta: { class: "auto-height" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide&quot; vaa-showhide=&quot;.vaa-settings-freeze-locale-desc&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;input type=&quot;checkbox&quot; id=&quot;vaa-settings-freeze-locale&quot; name=&quot;vaa_settings_freeze_locale&quot; value=&quot;1&quot; class=&quot;checkbox&quot; vaa-auto-js=&quot;{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:false,&quot;values&quot;:{&quot;freeze_locale&quot;:null}}&quot; /&gt;&lt;label class=&quot;ab-vaa-showhide&quot; for=&quot;vaa-settings-freeze-locale&quot;&gt;Freeze locale&lt;/label&gt;&lt;p class=&quot;ab-item description vaa-settings-freeze-locale-desc&quot;&gt;Force your own locale setting to the current view&lt;/p&gt;",
                                title_clean:
                                    "Freeze localeForce your own locale setting to the current view",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-view_types": {
                                icon: "",
                                id: "vaa-view_types",
                                title: false,
                                parent: "vaa-settings",
                                href: false,
                                group: true,
                                meta: { class: "ab-sub-secondary" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded: "",
                                title_clean: "",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-modules": {
                                icon: "",
                                id: "vaa-modules",
                                title: false,
                                parent: "vaa-settings",
                                href: false,
                                group: true,
                                meta: { class: "ab-sub-secondary" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded: "",
                                title_clean: "",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-settings-force-group-users": {
                                icon: "",
                                id: "vaa-settings-force-group-users",
                                title: '<span class="ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide" vaa-showhide=".vaa-settings-force-group-users-desc" aria-hidden="true"></span><input type="checkbox" id="vaa-settings-force-group-users" name="vaa_settings_force_group_users" value="1" class="checkbox" vaa-auto-js="{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:true,&quot;values&quot;:{&quot;force_group_users&quot;:null}}" /><label class="ab-vaa-showhide" for="vaa-settings-force-group-users">Group users</label><p class="ab-item description vaa-settings-force-group-users-desc">Group users under their assigned roles</p>',
                                parent: "vaa-settings",
                                href: false,
                                group: false,
                                meta: { class: "auto-height" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide&quot; vaa-showhide=&quot;.vaa-settings-force-group-users-desc&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;input type=&quot;checkbox&quot; id=&quot;vaa-settings-force-group-users&quot; name=&quot;vaa_settings_force_group_users&quot; value=&quot;1&quot; class=&quot;checkbox&quot; vaa-auto-js=&quot;{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:true,&quot;values&quot;:{&quot;force_group_users&quot;:null}}&quot; /&gt;&lt;label class=&quot;ab-vaa-showhide&quot; for=&quot;vaa-settings-force-group-users&quot;&gt;Group users&lt;/label&gt;&lt;p class=&quot;ab-item description vaa-settings-force-group-users-desc&quot;&gt;Group users under their assigned roles&lt;/p&gt;",
                                title_clean: "Group usersGroup users under their assigned roles",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-settings-force-ajax-users": {
                                icon: "",
                                id: "vaa-settings-force-ajax-users",
                                title: '<span class="ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide" vaa-showhide=".vaa-settings-force-ajax-users-desc" aria-hidden="true"></span><input type="checkbox" id="vaa-settings-force-ajax-users" name="vaa_settings_force_ajax_users" value="1" class="checkbox" vaa-auto-js="{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:true,&quot;values&quot;:{&quot;force_ajax_users&quot;:null}}" /><label class="ab-vaa-showhide" for="vaa-settings-force-ajax-users">AJAX search users</label><p class="ab-item description vaa-settings-force-ajax-users-desc">Force AJAX search for users</p>',
                                parent: "vaa-settings",
                                href: false,
                                group: false,
                                meta: { class: "auto-height" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;ab-icon dashicons dashicons-editor-help vaa-help ab-vaa-showhide&quot; vaa-showhide=&quot;.vaa-settings-force-ajax-users-desc&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;input type=&quot;checkbox&quot; id=&quot;vaa-settings-force-ajax-users&quot; name=&quot;vaa_settings_force_ajax_users&quot; value=&quot;1&quot; class=&quot;checkbox&quot; vaa-auto-js=&quot;{&quot;setting&quot;:&quot;user_setting&quot;,&quot;refresh&quot;:true,&quot;values&quot;:{&quot;force_ajax_users&quot;:null}}&quot; /&gt;&lt;label class=&quot;ab-vaa-showhide&quot; for=&quot;vaa-settings-force-ajax-users&quot;&gt;AJAX search users&lt;/label&gt;&lt;p class=&quot;ab-item description vaa-settings-force-ajax-users-desc&quot;&gt;Force AJAX search for users&lt;/p&gt;",
                                title_clean: "AJAX search usersForce AJAX search for users",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                        },
                        menu_level: 2,
                        menu_status: true,
                        title_encoded:
                            "&lt;span class=&quot;ab-icon dashicons dashicons-admin-settings&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;Settings",
                        title_clean: "Settings",
                        title_encoded_default: "",
                        title_clean_default: "",
                    },
                    "vaa-combine-views": {
                        icon: "",
                        id: "vaa-combine-views",
                        title: '<input type="checkbox" id="vaa-combine-views" name="vaa_combine_views" value="1" class="checkbox" /><label for="vaa-combine-views">Combine views</label><button vaa-condition-target="#vaa-combine-views" id="vaa-combine-views-apply" name="vaa_combine_views_apply" class="button button-primary ab-vaa-conditional vaa-alignright">Apply</button><ul id="vaa-combine-views-selection" class="ab-sub-secondary ab-vaa-results" style="display: none;"></ul>',
                        parent: "vaa",
                        href: false,
                        group: false,
                        meta: { title: "Make view combinations", class: "vaa-button-container" },
                        submenu: [],
                        menu_level: 2,
                        menu_status: true,
                        title_encoded:
                            "&lt;input type=&quot;checkbox&quot; id=&quot;vaa-combine-views&quot; name=&quot;vaa_combine_views&quot; value=&quot;1&quot; class=&quot;checkbox&quot; /&gt;&lt;label for=&quot;vaa-combine-views&quot;&gt;Combine views&lt;/label&gt;&lt;button vaa-condition-target=&quot;#vaa-combine-views&quot; id=&quot;vaa-combine-views-apply&quot; name=&quot;vaa_combine_views_apply&quot; class=&quot;button button-primary ab-vaa-conditional vaa-alignright&quot;&gt;Apply&lt;/button&gt;&lt;ul id=&quot;vaa-combine-views-selection&quot; class=&quot;ab-sub-secondary ab-vaa-results&quot; style=&quot;display: none;&quot;&gt;&lt;/ul&gt;",
                        title_clean: "Combine viewsApply",
                        title_encoded_default: "",
                        title_clean_default: "",
                    },
                    "vaa-caps": {
                        icon: "",
                        id: "vaa-caps",
                        title: false,
                        parent: "vaa",
                        href: false,
                        group: true,
                        meta: { class: "ab-sub-secondary" },
                        submenu: {
                            "vaa-caps-title": {
                                icon: "",
                                id: "vaa-caps-title",
                                title: '<span class="ab-icon dashicons dashicons-forms" aria-hidden="true"></span>Capabilities',
                                parent: "vaa-caps",
                                href: false,
                                group: false,
                                meta: { class: "vaa-has-icon ab-vaa-title", tabindex: "0" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;ab-icon dashicons dashicons-forms&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;Capabilities",
                                title_clean: "Capabilities",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                        },
                        menu_level: 2,
                        menu_status: true,
                        title_encoded: "",
                        title_clean: "",
                        title_encoded_default: "",
                        title_clean_default: "",
                    },
                    "vaa-roles": {
                        icon: "",
                        id: "vaa-roles",
                        title: false,
                        parent: "vaa",
                        href: false,
                        group: true,
                        meta: { class: "ab-sub-secondary" },
                        submenu: {
                            "vaa-roles-title": {
                                icon: "",
                                id: "vaa-roles-title",
                                title: '<span class="ab-icon dashicons dashicons-groups" aria-hidden="true"></span>Roles',
                                parent: "vaa-roles",
                                href: false,
                                group: false,
                                meta: {
                                    class: "vaa-has-icon ab-vaa-title ab-vaa-toggle active",
                                    tabindex: "0",
                                },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;ab-icon dashicons dashicons-groups&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;Roles",
                                title_clean: "Roles",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-roles-role-administrator": {
                                icon: "",
                                id: "vaa-roles-role-administrator",
                                title: '<span class="vaa-view-data" vaa-view-type="role" vaa-view-type-label="Role" vaa-view-value="administrator">Administrator</span>',
                                parent: "vaa-roles",
                                href: "http://localhost:10043/wp-admin/?action=view_admin_as&#038;view_admin_as%5Brole%5D=administrator&#038;_vaa_nonce=1f38457e07",
                                group: false,
                                meta: { title: "View as Administrator", class: "vaa-role-item" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;vaa-view-data&quot; vaa-view-type=&quot;role&quot; vaa-view-type-label=&quot;Role&quot; vaa-view-value=&quot;administrator&quot;&gt;Administrator&lt;/span&gt;",
                                title_clean: "Administrator",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-roles-role-editor": {
                                icon: "",
                                id: "vaa-roles-role-editor",
                                title: '<span class="vaa-view-data" vaa-view-type="role" vaa-view-type-label="Role" vaa-view-value="editor">Editor</span>',
                                parent: "vaa-roles",
                                href: "http://localhost:10043/wp-admin/?action=view_admin_as&#038;view_admin_as%5Brole%5D=editor&#038;_vaa_nonce=1f38457e07",
                                group: false,
                                meta: { title: "View as Editor", class: "vaa-role-item" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;vaa-view-data&quot; vaa-view-type=&quot;role&quot; vaa-view-type-label=&quot;Role&quot; vaa-view-value=&quot;editor&quot;&gt;Editor&lt;/span&gt;",
                                title_clean: "Editor",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-roles-role-author": {
                                icon: "",
                                id: "vaa-roles-role-author",
                                title: '<span class="vaa-view-data" vaa-view-type="role" vaa-view-type-label="Role" vaa-view-value="author">Author</span>',
                                parent: "vaa-roles",
                                href: "http://localhost:10043/wp-admin/?action=view_admin_as&#038;view_admin_as%5Brole%5D=author&#038;_vaa_nonce=1f38457e07",
                                group: false,
                                meta: { title: "View as Author", class: "vaa-role-item" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;vaa-view-data&quot; vaa-view-type=&quot;role&quot; vaa-view-type-label=&quot;Role&quot; vaa-view-value=&quot;author&quot;&gt;Author&lt;/span&gt;",
                                title_clean: "Author",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-roles-role-contributor": {
                                icon: "",
                                id: "vaa-roles-role-contributor",
                                title: '<span class="vaa-view-data" vaa-view-type="role" vaa-view-type-label="Role" vaa-view-value="contributor">Contributor</span>',
                                parent: "vaa-roles",
                                href: "http://localhost:10043/wp-admin/?action=view_admin_as&#038;view_admin_as%5Brole%5D=contributor&#038;_vaa_nonce=1f38457e07",
                                group: false,
                                meta: { title: "View as Contributor", class: "vaa-role-item" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;vaa-view-data&quot; vaa-view-type=&quot;role&quot; vaa-view-type-label=&quot;Role&quot; vaa-view-value=&quot;contributor&quot;&gt;Contributor&lt;/span&gt;",
                                title_clean: "Contributor",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-roles-role-subscriber": {
                                icon: "",
                                id: "vaa-roles-role-subscriber",
                                title: '<span class="vaa-view-data" vaa-view-type="role" vaa-view-type-label="Role" vaa-view-value="subscriber">Subscriber</span>',
                                parent: "vaa-roles",
                                href: "http://localhost:10043/wp-admin/?action=view_admin_as&#038;view_admin_as%5Brole%5D=subscriber&#038;_vaa_nonce=1f38457e07",
                                group: false,
                                meta: { title: "View as Subscriber", class: "vaa-role-item" },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;vaa-view-data&quot; vaa-view-type=&quot;role&quot; vaa-view-type-label=&quot;Role&quot; vaa-view-value=&quot;subscriber&quot;&gt;Subscriber&lt;/span&gt;",
                                title_clean: "Subscriber",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                            "vaa-visitor-view": {
                                icon: "",
                                id: "vaa-visitor-view",
                                title: '<span class="ab-icon dashicons dashicons-universal-access" aria-hidden="true"></span><span class="vaa-view-data" vaa-view-type="visitor" vaa-view-value="1">Site visitor</span>',
                                parent: "vaa-roles",
                                href: "#",
                                group: false,
                                meta: {
                                    title: "View as site visitor",
                                    class: "vaa-visitor-item vaa-has-icon vaa-menupop",
                                },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;ab-icon dashicons dashicons-universal-access&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;span class=&quot;vaa-view-data&quot; vaa-view-type=&quot;visitor&quot; vaa-view-value=&quot;1&quot;&gt;Site visitor&lt;/span&gt;",
                                title_clean: "Site visitor",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                        },
                        menu_level: 2,
                        menu_status: true,
                        title_encoded: "",
                        title_clean: "",
                        title_encoded_default: "",
                        title_clean_default: "",
                    },
                    "vaa-users": {
                        icon: "",
                        id: "vaa-users",
                        title: false,
                        parent: "vaa",
                        href: false,
                        group: true,
                        meta: { class: "ab-sub-secondary" },
                        submenu: {
                            "vaa-users-title": {
                                icon: "",
                                id: "vaa-users-title",
                                title: '<span class="ab-icon dashicons dashicons-admin-users" aria-hidden="true"></span>Users',
                                parent: "vaa-users",
                                href: false,
                                group: false,
                                meta: {
                                    class: "vaa-has-icon ab-vaa-title ab-vaa-toggle active",
                                    tabindex: "0",
                                },
                                submenu: [],
                                menu_level: 3,
                                menu_status: true,
                                title_encoded:
                                    "&lt;span class=&quot;ab-icon dashicons dashicons-admin-users&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;Users",
                                title_clean: "Users",
                                title_encoded_default: "",
                                title_clean_default: "",
                            },
                        },
                        menu_level: 2,
                        menu_status: true,
                        title_encoded: "",
                        title_clean: "",
                        title_encoded_default: "",
                        title_clean_default: "",
                    },
                },
                menu_level: 1,
                menu_status: true,
                title_encoded:
                    "&lt;span class=&quot;ab-label&quot;&gt;View As&lt;/span&gt;&lt;span class=&quot;ab-icon dashicons dashicons-hidden alignright&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;",
                title_clean: "View As",
                title_encoded_default: "",
                title_clean_default: "",
            },
        },
        menu_level: 0,
        menu_status: true,
        title_encoded: "",
        title_clean: "",
        title_encoded_default: "",
        title_clean_default: "",
    },
    "query-monitor": {
        icon: "",
        id: "query-monitor",
        title: "Query Monitor",
        parent: false,
        href: "#qm-overview",
        group: false,
        meta: [],
        submenu: {
            "query-monitor-placeholder": {
                icon: "",
                id: "query-monitor-placeholder",
                title: "Query Monitor",
                parent: "query-monitor",
                href: "#qm-overview",
                group: false,
                meta: [],
                submenu: [],
                menu_level: 1,
                menu_status: true,
                title_encoded: "Query Monitor",
                title_clean: "Query Monitor",
                title_encoded_default: "",
                title_clean_default: "",
            },
        },
        menu_level: 0,
        menu_status: true,
        title_encoded: "Query Monitor",
        title_clean: "Query Monitor",
        title_encoded_default: "",
        title_clean_default: "",
    },
};
